services: 
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - vs_net

  client:
    build: ./client
    networks:
      - vs_net

  rpc_db:
    build: ./rpc_db
    networks:
      - vs_net

networks:
  vs_net:
    driver: bridge
